name: MonPlugin
version: 1.5
author: sagitarius
main: fr.sagitarius.MonPlugin.MonPlugin
depend: [ActionBarAPI]
commands:
  start:
    description: Demarre affichage de la fleche et distance de la BASE.
    usage: /start
  end:
    description: Termine affichage de la fleche et distance de la BASE
    usage: /end
  save:
    description: Sauvegarde des coordonnees sous le nom choisi
    usage: /save <NomSauvegarde> <LocX> <LocY> <LocZ>  ||  /save <NomSauvegarde> 
  remove:
    description: Suprime les coordonnees du nom choisi
    usage: /rmove <NomSauvegarde>
  list:
    description: Liste les coordonnees sauvegarde 
    usage: /list
  tpmort:
    description: TP le joueur a la derniere coordonnee de sa mort sauvegarde  
    usage: /tpmort
  tpw:
    description: TP le joueur a la coordonnee <NomSauvegarde> qui avait ete sauvegarde precedement
    usage: /tpw <NomSauvegarde>
  quete:
    description: Liste les quetes du joueurs avec en vert les terminees et en rouge celle a faire...
    usage: /quete || /qt
    aliases: qt
  gui:
    description: Affiche une interface graphique... En TEST
    usage: /gui
  gmz:
    description: Passe tous les joueurs en Gamemode 0
    usage: /gmz
  gmu:
    description: Passe tous les joueurs en Gamemode 1
    usage: /gmu
